exports.LOOKUP_SCREENS_DIR = 'lookup'
exports.STANDALONE_EDITOR_DIR = 'standalone-editor'
exports.STANDALONE_COLLECTION_DIR = 'standalone-collection'
exports.STANDALONE_DETAILS_DIR = 'standalone-details'
exports.READONLY_COLLECTION_DIR = 'readonly-collection'
exports.MANAGEMENT_DIR = 'management'
exports.BLANK_DIR = 'blank'
